CREATE TABLE users (id VARCHAR(64) PRIMARY KEY, phone VARCHAR(32) UNIQUE);
CREATE TABLE hospitals (id VARCHAR(64) PRIMARY KEY, name VARCHAR(255));
CREATE TABLE queue_tokens (id VARCHAR(64) PRIMARY KEY, token_number VARCHAR(32));
